// legacy_vue_app/src/components/layout/Navbar.vue
<script setup>
import { ref } from 'vue'
import { 
  LayoutDashboard, 
  MessageSquare, 
  Users, 
  PiggyBank, 
  Mail,
  LogOut,
  Menu,
  X,
  ShieldAlert,
  User
} from 'lucide-vue-next'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { cn } from '@/lib/utils'
import Button from '@/components/ui/Button.vue'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const isOpen = ref(false)

async function handleLogout() {
  await auth.logout()
  router.push('/login')
}

const links = [
  { name: 'Dashboard', path: '/', icon: LayoutDashboard },
  { name: 'Erika', path: '/chat', icon: MessageSquare }, // Shortened for Navbar
  { name: 'Anagrafica', path: '/contacts', icon: Users },
  { name: 'Fundraising', path: '/fundraising', icon: PiggyBank },
  { name: 'Newsletter', path: '/newsletter', icon: Mail },
]
</script>

<template>
  <nav class="w-full bg-white border-b border-gray-200">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <!-- Logo & Brand -->
        <div class="flex items-center">
            <img src="/logo-cri.png" alt="CRI Venezia" class="h-10 w-auto" />
        </div>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex items-center space-x-1">
          <router-link 
            v-for="link in links" 
            :key="link.path" 
            :to="link.path"
            :class="cn(
              'flex items-center gap-2 px-3 py-2 rounded-md transition-colors text-sm font-medium',
              route.path === link.path 
                ? 'bg-red-50 text-red-600' 
                : 'text-gray-500 hover:text-red-600 hover:bg-gray-50'
            )"
          >
            <component :is="link.icon" class="w-4 h-4" />
            {{ link.name }}
          </router-link>

          <!-- Admin Link -->
          <router-link 
            v-if="auth.user?.role === 'admin'"
            to="/admin"
            :class="cn(
              'flex items-center gap-2 px-3 py-2 rounded-md transition-colors text-sm font-medium',
              route.path === '/admin' 
                ? 'bg-red-50 text-red-600' 
                : 'text-gray-500 hover:text-red-600 hover:bg-gray-50'
            )"
          >
            <ShieldAlert class="w-4 h-4" />
            Admin
          </router-link>
        </div>

        <!-- User / Logout (Desktop) -->
        <div class="hidden md:flex items-center gap-2">
          <router-link to="/profile">
              <Button variant="ghost" size="sm" class="text-gray-500 hover:text-[#CC0000] gap-2">
                <User class="w-4 h-4" />
                <span>Profilo</span>
              </Button>
          </router-link>

          <Button 
            variant="ghost" 
            size="sm"
            @click="handleLogout"
            class="text-gray-500 hover:text-red-600 gap-2"
          >
            <LogOut class="w-4 h-4" />
            <span>Esci</span>
          </Button>
        </div>

        <!-- Mobile Menu Button -->
        <div class="flex items-center md:hidden">
          <button @click="isOpen = !isOpen" class="text-gray-500 hover:text-red-600 focus:outline-none">
            <Menu v-if="!isOpen" class="w-6 h-6" />
            <X v-else class="w-6 h-6" />
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile Menu -->
    <div v-if="isOpen" class="md:hidden border-t border-gray-100">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white shadow-lg">
        <router-link 
          v-for="link in links" 
          :key="link.path" 
          :to="link.path"
          @click="isOpen = false"
          :class="cn(
            'flex items-center gap-3 px-3 py-3 rounded-md text-base font-medium transition-colors',
            route.path === link.path 
              ? 'bg-red-50 text-red-600' 
              : 'text-gray-600 hover:bg-gray-50 hover:text-red-600'
          )"
        >
          <component :is="link.icon" class="w-5 h-5" />
          {{ link.name }}
        </router-link>

        <router-link 
          v-if="auth.user?.role === 'admin'"
          to="/admin"
          @click="isOpen = false"
          :class="cn(
            'flex items-center gap-3 px-3 py-3 rounded-md text-base font-medium transition-colors',
            route.path === '/admin' 
              ? 'bg-red-50 text-red-600' 
              : 'text-gray-600 hover:bg-gray-50 hover:text-red-600'
          )"
        >
          <ShieldAlert class="w-5 h-5" />
          Admin Panel
        </router-link>
        
        <div class="border-t border-gray-100 my-2 pt-2 space-y-1">
            <router-link 
              to="/profile"
              @click="isOpen = false"
              class="flex w-full items-center gap-3 px-3 py-3 rounded-md text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-[#CC0000] transition-colors"
            >
              <User class="w-5 h-5" />
              Profilo
            </router-link>

            <button 
                @click="handleLogout"
                class="flex w-full items-center gap-3 px-3 py-3 rounded-md text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-red-600 transition-colors"
            >
                <LogOut class="w-5 h-5" />
                Esci
            </button>
        </div>
      </div>
    </div>
  </nav>
</template>

// components/layout/navbar.tsx
'use client'

import * as React from "react"
import Link from "next/link"
import { Menu, X } from "lucide-react"

import { cn } from "@/lib/utils"
// import { Icons } from "@/components/icons" // We can use CriIcon or just text for now
import { Button, buttonVariants } from "@/components/ui/button"
import {
    Sheet,
    SheetContent,
    SheetTrigger,
    SheetHeader,
    SheetTitle,
} from "@/components/ui/sheet"
import { UserNav } from "@/components/layout/user-nav"

interface NavItem {
    title: string
    href: string
    disabled?: boolean
}

const items: NavItem[] = [
    {
        title: "Home",
        href: "/",
    },
    {
        title: "Anagrafica",
        href: "/contacts",
    },
]

export function Navbar() {
    const [isOpen, setIsOpen] = React.useState(false)

    return (
        <header className="sticky top-0 z-40 w-full border-b bg-background">
            <div className="container flex h-16 items-center space-x-4 sm:justify-between sm:space-x-0">
                <div className="flex gap-6 md:gap-10">
                    <Link href="/" className="flex items-center space-x-2">
                        <span className="inline-block font-bold text-red-600 text-xl">CRI Venezia</span>
                    </Link>
                    <nav className="hidden md:flex gap-6">
                        {items?.map(
                            (item, index) =>
                                item.href && (
                                    <Link
                                        key={index}
                                        href={item.href}
                                        className={cn(
                                            "flex items-center text-sm font-medium text-muted-foreground",
                                            item.disabled && "cursor-not-allowed opacity-80",
                                            "hover:text-primary transition-colors"
                                        )}
                                    >
                                        {item.title}
                                    </Link>
                                )
                        )}
                    </nav>
                </div>
                <div className="flex flex-1 items-center justify-end space-x-4">
                    <div className="flex items-center space-x-4">
                        <UserNav />
                        <Sheet open={isOpen} onOpenChange={setIsOpen}>
                            <SheetTrigger asChild>
                                <Button variant="ghost" className="md:hidden p-0 w-10 h-10">
                                    <Menu className="h-6 w-6" />
                                    <span className="sr-only">Toggle Menu</span>
                                </Button>
                            </SheetTrigger>
                            <SheetContent side="right" className="pr-0">
                                <SheetHeader>
                                    <SheetTitle className="sr-only">Menu di Navigazione</SheetTitle>
                                </SheetHeader>
                                <div className="px-7">
                                    <Link href="/" className="flex items-center" onClick={() => setIsOpen(false)}>
                                        <span className="font-bold text-red-600">CRI Venezia</span>
                                    </Link>
                                </div>
                                <div className="flex flex-col gap-4 mt-8 px-7">
                                    {items.map((item, index) => (
                                        <Link
                                            key={index}
                                            href={item.href}
                                            className="text-lg font-medium hover:text-red-600"
                                            onClick={() => setIsOpen(false)}
                                        >
                                            {item.title}
                                        </Link>
                                    ))}
                                </div>
                            </SheetContent>
                        </Sheet>
                    </div>
                </div>
            </div>
        </header>
    )
}
