// legacy_vue_app/src/views/Signup.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'

const router = useRouter()
const auth = useAuthStore()

const firstName = ref('')
const lastName = ref('')
const email = ref('')
const password = ref('')
const loading = ref(false)
const error = ref('')
const successMessage = ref('')

async function handleSignup() {
  loading.value = true
  error.value = ''
  
  const fullName = `${firstName.value} ${lastName.value}`.trim()
  
  const { error: err } = await auth.signup({
    email: email.value,
    password: password.value,
    options: {
      data: {
        full_name: fullName,
        first_name: firstName.value,
        last_name: lastName.value
      },
      // Redirect URL for email confirmation
      emailRedirectTo: window.location.origin + '/login'
    }
  })
  
  if (err) {
    error.value = err.message
    loading.value = false
  } else {
    successMessage.value = 'Controlla la tua email per confermare la registrazione.'
    loading.value = false
  }
}
</script>

<template>
  <div class="flex items-center justify-center min-h-screen bg-gray-50 px-4">
    <Card class="w-full max-w-md">
      <div class="flex flex-col space-y-1.5 p-6">
        <h3 class="text-2xl font-bold text-center text-[#CC0000]">Registrazione</h3>
        <p class="text-sm text-muted-foreground text-center">Crea un account per CRI Venezia</p>
      </div>
      
      <div class="p-6 pt-0 space-y-4">
        <form @submit.prevent="handleSignup" class="space-y-4">
          
          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="firstName">Nome</Label>
              <Input id="firstName" v-model="firstName" placeholder="Mario" required autocomplete="given-name" />
            </div>
            <div class="space-y-2">
              <Label for="lastName">Cognome</Label>
              <Input id="lastName" v-model="lastName" placeholder="Rossi" required autocomplete="family-name" />
            </div>
          </div>

          <div class="space-y-2">
            <Label for="email">Email</Label>
            <Input id="email" type="email" v-model="email" placeholder="m@example.com" required autocomplete="username" />
          </div>
          <div class="space-y-2">
            <Label for="password">Password</Label>
            <Input id="password" type="password" v-model="password" required autocomplete="new-password" />
          </div>

          <div v-if="error" class="text-red-500 text-sm font-medium">
            {{ error }}
          </div>
           <div v-if="successMessage" class="text-green-600 text-sm font-medium">
            {{ successMessage }}
          </div>
          
          <div class="flex flex-col gap-2 pt-4">
            <Button type="submit" class="w-full bg-[#CC0000] hover:bg-[#990000] text-white" :disabled="loading">
              {{ loading ? "Caricamento..." : "Crea Account" }}
            </Button>
          </div>
          
          <div class="text-center text-sm mt-4">
            <router-link to="/login" class="text-muted-foreground hover:text-red-600 underline">
              Hai già un account? Accedi
            </router-link>
          </div>
        </form>
      </div>
    </Card>
  </div>
</template>

// app/signup/page.tsx
'use client'

import { useState } from 'react'
import { signup } from '@/app/login/actions'
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useToast } from "@/components/ui/use-toast"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { useRouter } from 'next/navigation'

export default function SignupPage() {
    const [loading, setLoading] = useState(false)
    const { toast } = useToast()
    const router = useRouter()

    const handleAction = async (formData: FormData) => {
        setLoading(true)

        try {
            const result = await signup(formData)
            if (result && 'error' in result && result.error) {
                toast({
                    variant: "destructive",
                    title: "Errore",
                    description: result.error,
                })
            } else if (result && 'message' in result && result.message) {
                toast({
                    title: "Successo",
                    description: result.message,
                })
                // Optional: Redirect to login or show success state
                router.push('/login')
            }
        } catch (error) {
            toast({
                variant: "destructive",
                title: "Critico",
                description: "Qualcosa è andato storto. Riprova.",
            })
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="flex items-center justify-center min-h-screen bg-gray-50 dark:bg-gray-900 px-4">
            <Card className="w-full max-w-md">
                <CardHeader className="space-y-1">
                    <CardTitle className="text-2xl font-bold text-center text-red-600">Registrazione</CardTitle>
                    <CardDescription className="text-center">
                        Crea un account per CRI Venezia
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">

                    <form action={handleAction} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="firstName">Nome</Label>
                                <Input id="firstName" name="firstName" type="text" placeholder="Mario" required />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="lastName">Cognome</Label>
                                <Input id="lastName" name="lastName" type="text" placeholder="Rossi" required />
                            </div>
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="email">Email</Label>
                            <Input id="email" name="email" type="email" placeholder="m@example.com" required />
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="password">Password</Label>
                            <Input id="password" name="password" type="password" required />
                        </div>

                        <div className="flex flex-col gap-2 pt-4">
                            <Button
                                type="submit"
                                className="w-full bg-red-600 hover:bg-red-700"
                                disabled={loading}
                            >
                                {loading ? "Caricamento..." : "Crea Account"}
                            </Button>
                        </div>
                        <div className="text-center text-sm mt-4">
                            <a href="/login" className="text-muted-foreground hover:text-red-600 underline">
                                Hai già un account? Accedi
                            </a>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    )
}
